# Generated by Django 6.0.4 on 2026-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaloryApp', '0002_alter_porfilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentrymodel',
            name='caloris',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='porfilemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
