# Generated by Django 6.0.2 on 2026-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seekermodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job_portal.skillmodel'),
        ),
        migrations.AddField(
            model_name='seekermodel',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job_portal.skillmodel'),
        ),
    ]
