# Generated by Django 6.0.2 on 2026-02-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_skillmodel_remove_seekermodel_skill_jobmodel_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='skills',
            new_name='required_skills',
        ),
    ]
