# Generated by Django 6.0.2 on 2026-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reviewmodel',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True),
        ),
    ]
